# Generated by Django 2.1.5 on 2019-09-15 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateTimeField()),
                ('challenge', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('account', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='AccountManager.Account')),
                ('moment', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='AccountManager.Moment')),
            ],
        ),
    ]
