# Generated by Django 2.1.5 on 2019-09-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManager', '0003_auto_20190915_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
