# Generated by Django 2.1.5 on 2019-09-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManager', '0004_auto_20190915_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='challenge',
            field=models.IntegerField(default=0),
        ),
    ]
