# Generated by Django 2.1.5 on 2019-09-15 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManager', '0005_auto_20190915_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='AccountManager.Account'),
        ),
    ]
