# Generated by Django 2.1.5 on 2019-09-15 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManager', '0006_moment_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='challenge',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='AccountManager.Challenge'),
        ),
    ]
